server.port=${PORT:8080}
logging.level.org.atmosphere = warn

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/prodeca}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:pr0decAU54R}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:6n!<kWBOOZe1Uwjrh}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

vaadin.launch-browser=${VAADIN_LAUNCH_BROWSER:true}
# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages = com.vaadin,org.vaadin,com.flowingcode,com.prodeca
spring.jpa.defer-datasource-initialization = true
spring.sql.init.mode = always